[install]
# 5-day quarantine: reject package versions published
# less than 5 days ago to mitigate supply chain attacks.
minimumReleaseAge = 432_000
minimumReleaseAgeExcludes = [
  "@stll/typescript-config", # quarantine-excluded-since: 2026-05-31T22:16:56.000Z
  "@stll/oxlint-config", # quarantine-excluded-since: 2026-05-31T22:16:56.000Z
  "@stll/regex-set-darwin-x64", # quarantine-excluded-since: 2026-04-15T13:00:54.000Z
  "@stll/regex-set-darwin-arm64", # quarantine-excluded-since: 2026-04-15T13:00:54.000Z
  "@stll/regex-set-linux-x64-gnu", # quarantine-excluded-since: 2026-04-15T13:00:54.000Z
  "@stll/regex-set-linux-arm64-gnu", # quarantine-excluded-since: 2026-04-15T13:00:54.000Z
  "@stll/regex-set-wasm32-wasi", # quarantine-excluded-since: 2026-04-15T13:00:54.000Z
]
