/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RegexSet {
  constructor(patterns: Array<string>, options?: Options | undefined | null)
  get patternCount(): number
  isMatch(haystack: string): boolean
  _findIterPacked(haystack: string): Uint32Array
  whichMatch(haystack: string): Array<number>
  replaceAll(haystack: string, replacements: Array<string>): string
}

/** A single match returned by search methods. */
export interface Match {
  /** Index of the pattern that matched. */
  pattern: number
  /** Start offset (UTF-16 code units). */
  start: number
  /** End offset (exclusive, UTF-16 code units). */
  end: number
}

/** Options for constructing a `RegexSet`. */
export interface Options {
  /**
   * Only match whole words. Default: `false`.
   * Wraps each pattern with `\b...\b`.
   */
  wholeWords?: boolean
}
