/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Patterns split into two DFAs: fast (find_iter)
 * and slow (manual loop with shadowed check).
 * This prevents 2 lookahead patterns from forcing
 * all 15 other patterns onto the slow path.
 */
export declare class RegexSet {
  constructor(patterns: Array<string>, options?: Options | undefined | null)
  get patternCount(): number
  isMatch(haystack: string): boolean
  _isMatchBuf(haystack: Buffer): boolean
  _findIterPacked(haystack: string): Uint32Array
  _findIterPackedBuf(haystack: Buffer): Uint32Array
  whichMatch(haystack: string): Array<number>
  replaceAll(haystack: string, replacements: Array<string>): string
}

/**
 * Compute UAX#29 word boundary positions using
 * the unicode-segmentation crate. Returns the
 * set as a sorted Vec of byte offsets.
 */
export declare function _uax29Boundaries(haystack: Buffer): Array<number>

/** A single match returned by search methods. */
export interface Match {
  /** Index of the pattern that matched. */
  pattern: number
  /** Start offset (UTF-16 code units). */
  start: number
  /** End offset (exclusive, UTF-16 code units). */
  end: number
}

/** Options for constructing a `RegexSet`. */
export interface Options {
  /** Only match whole words. Default: `false`. */
  wholeWords?: boolean
  /**
   * Use Unicode word boundaries. Default: `false`.
   *
   * When `true`, `\b` matches at Unicode word
   * boundaries (accented letters, CJK, etc. are
   * word chars). When `false`, `\b` uses ASCII
   * semantics matching JS `RegExp` behavior.
   *
   * Implementation: edge `\b` is stripped from the
   * pattern and verified inline per match (O(1)),
   * so there is zero DFA overhead regardless of
   * which mode is used.
   */
  unicodeBoundaries?: boolean
}
