/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RegexSet {
  constructor(patterns: Array<string>, options?: Options | undefined | null, prepared?: Buffer | undefined | null)
  get patternCount(): number
  isMatch(haystack: string): boolean
  _isMatchBuf(haystack: Buffer): boolean
  _findIterPacked(haystack: string): Uint32Array
  _findIterPackedBuf(haystack: Buffer): Uint32Array
  whichMatch(haystack: string): Array<number>
  replaceAll(haystack: string, replacements: Array<string>): string
}

export declare function _prepareRegexSet(patterns: Array<string>, options?: Options | undefined | null): Buffer

export declare function _uax29Boundaries(haystack: Buffer): Array<number>

export interface Match {
  pattern: number
  start: number
  end: number
}

export interface Options {
  wholeWords?: boolean
  unicodeBoundaries?: boolean
}
