import { spawnSync } from "node:child_process";
import { constants } from "node:fs";
import {
  access,
  readFile,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import { fileURLToPath } from "node:url";

const cliPath = new URL(
  "../node_modules/@napi-rs/cli/dist/cli.js",
  import.meta.url,
);

const result = spawnSync(
  process.execPath,
  [
    fileURLToPath(cliPath),
    "build",
    ...process.argv.slice(2),
  ],
  {
    stdio: "inherit",
  },
);

if (result.status !== 0) {
  process.exit(result.status ?? 1);
}

const typecheckBanner =
  "// @ts-nocheck -- generated by @napi-rs/cli\n";

async function normalizeGeneratedFile(
  fileName,
  { disableTypecheck = false } = {},
) {
  const fileUrl = new URL(`../${fileName}`, import.meta.url);
  try {
    let content = await readFile(fileUrl, "utf8");
    if (
      disableTypecheck &&
      !content.startsWith(typecheckBanner)
    ) {
      content = `${typecheckBanner}${content}`;
    }
    await writeFile(
      fileUrl,
      content.replace(/[ \t]+$/gm, ""),
    );
  } catch (error) {
    if (error?.code !== "ENOENT") {
      throw error;
    }
  }
}

await normalizeGeneratedFile(
  "regex-set.wasi-browser.js",
  { disableTypecheck: true },
);
await normalizeGeneratedFile("wasi-worker-browser.mjs");
await normalizeGeneratedFile("wasi-worker.mjs");

const source = new URL("../index.js", import.meta.url);
const target = new URL("../index.cjs", import.meta.url);

try {
  await access(source, constants.F_OK);
} catch {
  process.exit(0);
}

await rm(target, { force: true });
await rename(source, target);
