import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const cliPath = new URL(
  "../node_modules/@napi-rs/cli/dist/cli.js",
  import.meta.url,
);

const result = spawnSync(
  process.execPath,
  [
    fileURLToPath(cliPath),
    "build",
    "--js",
    "index.cjs",
    ...process.argv.slice(2),
  ],
  {
    stdio: "inherit",
  },
);

if (result.status !== 0) {
  process.exit(result.status ?? 1);
}

const typecheckBanner =
  "// @ts-nocheck -- generated by @napi-rs/cli\n";

async function normalizeGeneratedFile(
  fileName,
  { disableTypecheck = false } = {},
) {
  const fileUrl = new URL(
    `../${fileName}`,
    import.meta.url,
  );
  try {
    let content = await readFile(fileUrl, "utf8");
    if (
      disableTypecheck &&
      !content.startsWith(typecheckBanner)
    ) {
      content = `${typecheckBanner}${content}`;
    }
    await writeFile(
      fileUrl,
      content.replace(/[ \t]+$/gm, ""),
    );
  } catch (error) {
    if (error?.code !== "ENOENT") {
      throw error;
    }
  }
}

await normalizeGeneratedFile("regex-set.wasi-browser.js", {
  disableTypecheck: true,
});
await normalizeGeneratedFile("wasi-worker-browser.mjs");
await normalizeGeneratedFile("wasi-worker.mjs");

const contractResult = spawnSync(
  "bun",
  [
    fileURLToPath(
      new URL("./wasi-artifact-contract.mjs", import.meta.url),
    ),
    "--generated",
  ],
  { stdio: "inherit" },
);

if (contractResult.status !== 0) {
  process.exit(contractResult.status ?? 1);
}
