name: Provenance Nightly

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  provenance-update:
    permissions:
      contents: write
      pull-requests: write
    uses: stella/.github/.github/workflows/provenance-update.yml@27c264db9f53ff3128118c773879d71cf9e586b8
    secrets: inherit
    with:
      install-command: bun install --frozen-lockfile
      provenance-version: v0.1.0
