name: Release PR

on:
  push:
    branches: [main]

concurrency:
  group: release-pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  version:
    uses: stella/.github/.github/workflows/changeset-release-pr.yml@5628b97fb3c560c0d961baa60c272c598eddcab5 # v1.7.0
    secrets:
      CHANGELOG_APP_ID: ${{ secrets.CHANGELOG_APP_ID }}
      CHANGELOG_APP_PRIVATE_KEY: ${{ secrets.CHANGELOG_APP_PRIVATE_KEY }}
