name: Release PR

on:
  push:
    branches: [main]

concurrency:
  group: release-pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  version:
    uses: stella/.github/.github/workflows/changeset-release-pr.yml@6c814558499cf9792072dad3bb36ca3983202dd2 # v1.5.0
    secrets:
      CHANGELOG_APP_ID: ${{ secrets.CHANGELOG_APP_ID }}
      CHANGELOG_APP_PRIVATE_KEY: ${{ secrets.CHANGELOG_APP_PRIVATE_KEY }}
